apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: dummypod
  ports:
    - port: 80          # Service port
      LoadBalancer: 80    # Container port  